app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_v1:
    type: rest
    prefix: /api/v1
    resource: "@AppBundle/Resources/config/routes_api_v1.yml"

api_v2:
    type: rest
    prefix: /api/v2
    resource: "@AppBundle/Resources/config/routes_api_v2.yml"
